### ISSUE TITLE
Objeto 3D en Blender

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-remi-team-1#1]
[Reporte 2 - Objeto 3D.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-diseno-de-objeto-3d-en-blender-remi-team-1/files/11107347/Reporte.2.-.Objeto.3D.pdf)

**Comment by bg55-a** [comment]
calificacion: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
